### ISSUE TITLE
Curious about the 1-second granularity

### ISSUE THREAD

**Issue by amanka** [yusuzech/timeR#1]
Thanks for making the package. I like how easy it is to use, and getting the results as a DF.

But I've noticed that it's hardcoded to provide 1-second granularity in all its results. [Ex. here](https://github.com/yusuzech/timeR/blob/8c4c98be6f3a2e08fe7d85727472eb61fcaaff60/R/timer_class.R#L137)

To me it would make sense to store as much granularity as possible (or at least down to the ms) and then display at a granularity that makes sense, perhaps offloading that decision to Lubridate or exposing the option to the user.

**Comment by yusuzech** [comment]
Hi,

I totally agree that it's better to have more granularity. The 1 second thing was a ugly walk-around to solve a bug in Rmarkdown that it causes error when displaying posixct/posixlt in dataframe. I can work on this issue by this weekend and I'll let you know once I fix it.

Best
________________________________

**Comment by yusuzech** [comment]
@amanka 

The line you point out is to force use second as unit, it was integers because start and end time was converted from yyyy-mm-dd hh:mm:ss format where the precision is second . 

The reason for this kind of awkwardness is that the default POSIXlt is causing some many unwanted problems (timezone, locale etc.) and it  usually displays incorrectly when the data frame is exported to csv or excel.

For easier management, I forced the type start and end column to be string.

--------------------------

I just fixed it by adding another argument **precision** when creating a `timeR` object. Precision is default to "s"(second) so the behavior should persist in your previous codes. 

Now you can use 
`mytimer = CreateTimer(precision = "ms")` 
or `mytimer = CreateTimer(precision = "us")` 
to specify precision to millisecond and microsecond.

Please use `devtools::install_github("yusuzech/timeR")` to install the update since the update is not on CRAN yet.

Thanks

**Comment by amanka** [comment]
Thank you!
